### ISSUE TITLE
Implement !new and !join

### ISSUE THREAD

**Issue by chrisgillis** [chrisgillis/slackwolf#19]
After playing a lot in Slack, it seems like it would be better if we moved more to a 'i want to start a new game, everyone !join it' rather than '!start @user1 @user2 @user3' or '!start' (rarely everyone is at keyboard)

I want to move to a system that looks more like this

Usage: !new <mode> <min-players-to-start>
@me: !new Classic 6
@user1: !join
@werewolf-bot: Classic 6 players: @user1
@user2: !join
@werewolf-bot: Classic 6 players: @user1,@user2
@user3: !new Classic 4
@werewolf-bot: Lobby already in progress.
@me: !start
@werewolf-bot: Not enough players to start yet.
@me: !end
@werewolf-bot: Game cancelled.

**Comment by ThatOneGuyDotNet** [comment]
partially Implemented in #26 
The game types/number of players is not implemented, you create a !new lobby, people !join it, then you !start it. The ability to specify the game type/players should be done at the same time as it is done for #4.  

Also changed the default '!start' for an entire room to '!start all' because even before this change people were starting whole room games when they didn't mean to.

**Comment by chrisgillis** [comment]
Yeah after all your changes this could actually be implemented in !setoption

**Comment by ThatOneGuyDotNet** [comment]
I guess I don't see what you mean.  The way I implemented it still allows the same functionality without adding another option.  Sure some people that use the current !start command might have to re-learn to change it to '!start all'. We could change the !start command to be smart enough to sense that no parameters were passed and a lobby isn't started and return a message like "A lobby has not been created.  Use `!new` to start a new lobby, `!start all` to start a game with all players in the room or `!start @user1 @user2 @user3` to start a game with the provided players."

Thoughts?

**Comment by chrisgillis** [comment]
Oops, take my comment and imagine it was on #4 instead :P
