### ISSUE TITLE
Pentakill!

### ISSUE THREAD

**Issue by sarfrazb** [chrisgillis/slackwolf#33]
Hi!

Absolutely loving the game!
We implemented it in our organisation and are having lots of fun with it.
We're not super tech-savvy (and we may play by different rules), so this may come across as an ignorant question, but we were wondering if the following was a bug or a feature:
We had a 5-way split vote, each with 1 vote. The result was that all 5 votees died.
This has also been seen with a 2-way split vote.

Was just wondering if bug or feature!
I've attached a screenshot for you below:
Thanks for providing an amazing bonding experience for our team :)
<img width="816" alt="screen shot 2016-05-12 at 8 24 26 pm" src="https://cloud.githubusercontent.com/assets/13691330/15211601/91ca8080-187f-11e6-8990-e542af31f59f.png">

**Comment by hueyl77** [comment]
Haha that's hilarious!  So there was a 5 way tie and all 5 people got lynched?  That doesn't happen to often.

From what I can gather from the code, it's straight forward logic.  If there is a tie all the highest "tied" targets got lynched.  The logic here can improve a bit, namely:

1. Allow an option to be set to that if there is a tie, everyone has to revote.
or
2. If there is a tie, noone gets hanged.

Which do you guys think makes more sense?

 @chrisgilli @awright022 @AshleyPinner

**Comment by AshleyPinner** [comment]
Nice pentakill. I *guess* the village wins as the werewolf died first, but if I were GMing a game I'd vary between the options depending on comedic value. 

But on a general case, a tie calls for a revote of the highest _n_ voted people. In this case, it'd be a revote with everyone as possible candidates. If you had a 2-way tie from, say 3 or 4 nominations, everyone would revote only on the two people who tied.

A tie after this would kill no-one.

I'd also code in the concept of vote nullification, for if after hearing the reasons why the village shouldn't lynch the nominated, and it turned out that all of them were useful roles (or good liars), it should be possible for the village to refuse to vote and thus no-one dies, rather than triggering the tie voting. (This also allows werewolves to clearly sabotage the voting!)

**Comment by awright022** [comment]
When I've played in real life a tie has always been a no-one-dies.  This also makes elements like the Sasquatch role more unpredictable/menacing.  I'd be for making that a configurable change (1 = tied parties die, 2 = no one dies, 3 = revote until one party has more votes than the other).  I don't really like the revote option, personally, as it extends the game and can draw out the daytime portion of the game excessively.

**Comment by chrisgillis** [comment]
Love the idea of making it a configurable change.

In my group we dont have a problem with games taking too long and we'd love to revote. This also gives everyone a chance to see how everyone voted giving more information.

**Comment by chrisgillis** [comment]
I thought about this some more and want to hear some feedback from you guys. I was reading the Ultimate Werewolf rules and they actually recommend using an accusation system for voting instead of how slackwolf works.

You'd accuse someone with !accuse @player and werewolf bot would say something like "@player has been accused!". That message would have two slack "reactions" added for thumbs up and thumbs down and the rest of the players click on the reaction to vote. Once all the votes have been received, majority thumbsup equals a kill otherwise, nothing happens and we wait for the next accusation.

I like this because of how much information can be spread through voting which I think would bring a lot of value to a chatroom game.

I hear you guys that play in more of a turn-based manner (not everyone focused on the chat channel) so ideally this voting mechanism could be turned on or off.

**Comment by zkleinfeld** [comment]
I'd be interested in alternate voting options, but this exact issue should be mostly fixed in #41, if "no lynching happens, but there is no revote" is a satisfactory fix. Also note there's an outstanding issue where "noone" will not properly tie with a lynched player.

**Comment by chrisgillis** [comment]
Thanks for the fix!
